
#include <hi_types.h>
#include <hi_mdm_types.h>
#include "sal_common.h"
#include <os_res_types.h>
#include "hi_ft_nv.h"
#if defined(PRODUCT_CFG_SUPPORT_CONFIG_VARIABLE)
#if defined (PRODUCT_CFG_PRODUCT_TYPE_CCO)
HI_CONST HI_U32 PRODUCT_CFG_UPG1_REAL_FLASH_ADDR                = PRODUCT_CFG_CCO_UPG1_REAL_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_UPG2_REAL_FLASH_ADDR                = PRODUCT_CFG_CCO_UPG2_REAL_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_NV_FLASH_ADDR                       = PRODUCT_CFG_CCO_NV_FLASH_ADDR_U;
#elif defined (PRODUCT_CFG_PRODUCT_TYPE_STA)
HI_CONST HI_U32 PRODUCT_CFG_UPG1_REAL_FLASH_ADDR                = PRODUCT_CFG_STA_UPG1_REAL_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_UPG2_REAL_FLASH_ADDR                = PRODUCT_CFG_STA_UPG2_REAL_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_NV_FLASH_ADDR                       = PRODUCT_CFG_STA_NV_FLASH_ADDR_U;
#elif defined (PRODUCT_CFG_PRODUCT_TYPE_NDM)
HI_CONST HI_U32 PRODUCT_CFG_UPG1_REAL_FLASH_ADDR                = PRODUCT_CFG_NDM_UPG1_REAL_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_UPG2_REAL_FLASH_ADDR                = PRODUCT_CFG_NDM_UPG2_REAL_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_NV_FLASH_ADDR                       = PRODUCT_CFG_NDM_NV_FLASH_ADDR_U;
#elif defined (PRODUCT_CFG_CORE_TYPE_BOOTLOADER)
HI_U32 PRODUCT_CFG_UPG1_REAL_FLASH_ADDR                         = PRODUCT_CFG_CCO_UPG1_REAL_FLASH_ADDR_U;
HI_U32 PRODUCT_CFG_UPG2_REAL_FLASH_ADDR                         = PRODUCT_CFG_CCO_UPG2_REAL_FLASH_ADDR_U;
HI_U32 PRODUCT_CFG_NV_FLASH_ADDR                                = PRODUCT_CFG_CCO_NV_FLASH_ADDR_U;
HI_U32 PRODUCT_CFG_UPG1_FILE_FLASH_ADDR                         = PRODUCT_CFG_UPG1_FILE_FLASH_ADDR_U;
HI_U32 PRODUCT_CFG_UPG2_FILE_FLASH_ADDR                         = PRODUCT_CFG_UPG2_FILE_FLASH_ADDR_U;
#endif
HI_CONST HI_U32 PRODUCT_CFG_UPG_CRC_BLK_SIZE                    = PRODUCT_CFG_UPG_CRC_BLK_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_UPG_NVFILE_FLASH_SIZE               = PRODUCT_CFG_UPG_NVFILE_FLASH_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_BOOT_FLASH_SIZE                     = PRODUCT_CFG_BOOT_FLASH_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_BOOT_VERSION_ADDR                   = PRODUCT_CFG_BOOT_VERSION_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_CRASH_FLASH_ADDR                    = PRODUCT_CFG_CRASH_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_UPGFILE_CACHE_CCO_FLASH_ADDR        = PRODUCT_CFG_UPGFILE_CACHE_CCO_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_UPGFILE_CACHE_CCO_FLASH_SIZE        = PRODUCT_CFG_UPGFILE_CACHE_CCO_FLASH_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_UPGFILE_CACHE_CCO_RAM_SIZE          = PRODUCT_CFG_UPGFILE_CACHE_CCO_RAM_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_UPG_LIST_CCO_FLASH_ADDR             = PRODUCT_CFG_UPG_LIST_CCO_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_UPG_LIST_CCO_FLASH_SIZE             = PRODUCT_CFG_UPG_LIST_CCO_FLASH_SIZE_U; 
HI_CONST HI_U32 PRODUCT_CFG_USERDATA_CCO_BIDB_FLASH_ADDR        = PRODUCT_CFG_USERDATA_CCO_BIDB_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_USERDATA_CCO_APP_FLASH_ADDR         = PRODUCT_CFG_USERDATA_CCO_APP_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_USERDATA_CCO_USER_FLASH_ADDR        = PRODUCT_CFG_USERDATA_CCO_USER_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_DIAG_CCO_FLASH_ADDR                 = PRODUCT_CFG_DIAG_CCO_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_DIAG_STA_FLASH_ADDR                 = PRODUCT_CFG_DIAG_STA_FLASH_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_DEFAULT_STATIC_MEM_SIZE             = PRODUCT_CFG_DEFAULT_STATIC_MEM_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_DEFAULT_DYN_MEM_SIZE                = PRODUCT_CFG_DEFAULT_DYN_MEM_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_CCO_UPG_FILE_MAX_SIZE               = PRODUCT_CFG_CCO_UPG_FILE_MAX_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_STA_UPG_FILE_MAX_SIZE               = PRODUCT_CFG_STA_UPG_FILE_MAX_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_NDM_UPG_FILE_MAX_SIZE               = PRODUCT_CFG_NDM_UPG_FILE_MAX_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_WD_INT_PROC_ENABLE                  = PRODUCT_CFG_WD_INT_PROC_ENABLE_U;
HI_CONST HI_U32 PRODUCT_CFG_POWER_DOWN_ETH_PHY_ENABLE           = PRODUCT_CFG_POWER_DOWN_ETH_PHY_ENABLE_U;
HI_CONST HI_U32 PRODUCT_CFG_SDM_ENG_EVT_FLASH_SIZE              = PRODUCT_CFG_SDM_ENG_EVT_FLASH_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_BOOT_DYNAMIC_ADDR_END               = PRODUCT_CFG_BOOT_DYNAMIC_ADDR_END_U;
HI_CONST HI_U32 PRODUCT_CFG_CCO_PERIOD_SIZE                     = PRODUCT_CFG_CCO_PERIOD_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_STA_PERIOD_SIZE                     = PRODUCT_CFG_STA_PERIOD_SIZE_U;
HI_CONST HI_U32 PRODUCT_CFG_SDM_BAT_FLASH_ST_ADDR               = PRODUCT_CFG_SDM_BAT_FLASH_ST_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_SDM_BAT_FLASH_END_ADDR              = PRODUCT_CFG_SDM_BAT_FLASH_END_ADDR_U;
HI_CONST HI_U32 PRODUCT_CFG_NV_FLASH_ITEM_SIZE_MAX              = PRODUCT_CFG_NV_FLASH_ITEM_SIZE_MAX_U;
HI_CONST HI_U32 PRODUCT_CFG_UPG_BITMAP_LEN                      = PRODUCT_CFG_UPG_BITMAP_LEN_U;
HI_CONST HI_U32 PRODUCT_CFG_ETH_PHY_ADDR_CFG                    = PRODUCT_CFG_ETH_PHY_ADDR_CFG_U;
HI_CONST HI_U32 PRODUCT_CFG_UPG_FILE_MAX_SIZE                   = PRODUCT_CFG_UPG_FILE_MAX_SIZE_NEW_U;
HI_CONST HI_U32 PRODUCT_CFG_NV_FILE_SIZE_MAX                    = PRODUCT_CFG_NV_FILE_SIZE_MAX_NEW;
HI_CONST HI_U32 PRODUCT_CFG_MCORE_RAM_HIGH_ADDR                 = PRODUCT_CFG_MCORE_RAM_HIGH_ADDR_U;
HI_CONST HI_U16 PRODUCT_CFG_TCP_PORT_MIN                        = PRODUCT_CFG_TCP_PORT_MIN_U;
HI_CONST HI_U16 PRODUCT_CFG_TCP_PORT_DIAG                       = PRODUCT_CFG_TCP_PORT_DIAG_U;
HI_CONST HI_U16 PRODUCT_CFG_TCP_PORT_MAX                        = PRODUCT_CFG_TCP_PORT_MAX_U;
HI_CONST HI_U8  PRODUCT_CFG_CHIP_MODE                           = PRODUCT_CFG_CHIP_MODE_U;
HI_CONST HI_U16 PRODUCT_CFG_DIAG_COMPANY_ID                     = PRODUCT_CFG_DIAG_COMPANY_ID_U;
HI_CONST HI_U16 PRODUCT_CFG_CMD_NV_READ_PLC                     = PRODUCT_CFG_CMD_NV_READ_PLC_U;
HI_CONST HI_U16 PRODUCT_CFG_CMD_NV_WRITE_PLC                    = PRODUCT_CFG_CMD_NV_WRITE_PLC_U;
HI_CONST HI_U16 PRODUCT_CFG_MMTYPE_DFX_MGT_PV100                = PRODUCT_CFG_MMTYPE_DFX_MGT_PV100_U;
HI_CONST HI_U16 PRODUCT_CFG_MMTYPE_NDM_CONNECT_PK               = PRODUCT_CFG_MMTYPE_NDM_CONNECT_PK_U;

HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_UNKOWN				= HI_FTM_PRODUCT_TYPE_UNKOWN;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C01					= HI_FTM_PRODUCT_TYPE_C01;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C02					= HI_FTM_PRODUCT_TYPE_C02;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C03					= HI_FTM_PRODUCT_TYPE_C03;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C04					= HI_FTM_PRODUCT_TYPE_C04;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C05					= HI_FTM_PRODUCT_TYPE_C05;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C06					= HI_FTM_PRODUCT_TYPE_C06;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C07					= HI_FTM_PRODUCT_TYPE_C07;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C08					= HI_FTM_PRODUCT_TYPE_C08;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C11					= HI_FTM_PRODUCT_TYPE_C11;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C12					= HI_FTM_PRODUCT_TYPE_C12;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C13					= HI_FTM_PRODUCT_TYPE_C13;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C14					= HI_FTM_PRODUCT_TYPE_C14;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C15					= HI_FTM_PRODUCT_TYPE_C15;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C16					= HI_FTM_PRODUCT_TYPE_C16;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C17					= HI_FTM_PRODUCT_TYPE_C17;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_C18					= HI_FTM_PRODUCT_TYPE_C18;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R21					= HI_FTM_PRODUCT_TYPE_R21;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R22					= HI_FTM_PRODUCT_TYPE_R22;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R23					= HI_FTM_PRODUCT_TYPE_R23;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R24					= HI_FTM_PRODUCT_TYPE_R24;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R25					= HI_FTM_PRODUCT_TYPE_R25;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R26					= HI_FTM_PRODUCT_TYPE_R26;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R27					= HI_FTM_PRODUCT_TYPE_R27;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R28					= HI_FTM_PRODUCT_TYPE_R28;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_T31					= HI_FTM_PRODUCT_TYPE_T31;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_T32					= HI_FTM_PRODUCT_TYPE_T32;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_T33					= HI_FTM_PRODUCT_TYPE_T33;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_T34					= HI_FTM_PRODUCT_TYPE_T34;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R35					= HI_FTM_PRODUCT_TYPE_R35;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R36					= HI_FTM_PRODUCT_TYPE_R36;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R37					= HI_FTM_PRODUCT_TYPE_R37;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_R38					= HI_FTM_PRODUCT_TYPE_R38;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D41					= HI_FTM_PRODUCT_TYPE_D41;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D42					= HI_FTM_PRODUCT_TYPE_D42;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D43					= HI_FTM_PRODUCT_TYPE_D43;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D44					= HI_FTM_PRODUCT_TYPE_D44;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D45					= HI_FTM_PRODUCT_TYPE_D45;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D46					= HI_FTM_PRODUCT_TYPE_D46;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D47					= HI_FTM_PRODUCT_TYPE_D47;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D48					= HI_FTM_PRODUCT_TYPE_D48;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D51					= HI_FTM_PRODUCT_TYPE_D51;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D52					= HI_FTM_PRODUCT_TYPE_D52;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D53					= HI_FTM_PRODUCT_TYPE_D53;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D54					= HI_FTM_PRODUCT_TYPE_D54;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D55					= HI_FTM_PRODUCT_TYPE_D55;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D56					= HI_FTM_PRODUCT_TYPE_D56;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D57					= HI_FTM_PRODUCT_TYPE_D57;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D58					= HI_FTM_PRODUCT_TYPE_D58;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D61					= HI_FTM_PRODUCT_TYPE_D61;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D62					= HI_FTM_PRODUCT_TYPE_D62;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D63					= HI_FTM_PRODUCT_TYPE_D63;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_D64					= HI_FTM_PRODUCT_TYPE_D64;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M101					= HI_FTM_PRODUCT_TYPE_M101;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M102					= HI_FTM_PRODUCT_TYPE_M102;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M103					= HI_FTM_PRODUCT_TYPE_M103;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M104					= HI_FTM_PRODUCT_TYPE_M104;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M105					= HI_FTM_PRODUCT_TYPE_M105;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M106					= HI_FTM_PRODUCT_TYPE_M106;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M107					= HI_FTM_PRODUCT_TYPE_M107;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M108					= HI_FTM_PRODUCT_TYPE_M108;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M111					= HI_FTM_PRODUCT_TYPE_M111;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M112					= HI_FTM_PRODUCT_TYPE_M112;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M113					= HI_FTM_PRODUCT_TYPE_M113;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M114					= HI_FTM_PRODUCT_TYPE_M114;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M115					= HI_FTM_PRODUCT_TYPE_M115;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M116					= HI_FTM_PRODUCT_TYPE_M116;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M117					= HI_FTM_PRODUCT_TYPE_M117;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M118					= HI_FTM_PRODUCT_TYPE_M118;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M119					= HI_FTM_PRODUCT_TYPE_M119;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M120					= HI_FTM_PRODUCT_TYPE_M120;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M121					= HI_FTM_PRODUCT_TYPE_M121;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M122					= HI_FTM_PRODUCT_TYPE_M122;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M123					= HI_FTM_PRODUCT_TYPE_M123;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M124					= HI_FTM_PRODUCT_TYPE_M124;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M125					= HI_FTM_PRODUCT_TYPE_M125;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M126					= HI_FTM_PRODUCT_TYPE_M126;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M131					= HI_FTM_PRODUCT_TYPE_M131;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M132					= HI_FTM_PRODUCT_TYPE_M132;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M133					= HI_FTM_PRODUCT_TYPE_M133;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M134					= HI_FTM_PRODUCT_TYPE_M134;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M135					= HI_FTM_PRODUCT_TYPE_M135;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M136					= HI_FTM_PRODUCT_TYPE_M136;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M137					= HI_FTM_PRODUCT_TYPE_M137;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_M138					= HI_FTM_PRODUCT_TYPE_M138;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_ANY					= HI_FTM_PRODUCT_TYPE_ANY;
HI_CONST HI_U32 HI_FTM_PRODUCT_TYPE_VALUE_MAX					= HI_FTM_PRODUCT_TYPE_MAX;

HI_CONST HI_U32 HI_FTM_PRODUCT_BOOTID_BASE_VALUE                = HI_FTM_PRODUCT_BOOTID_BASE;
#if defined(PRODUCT_CFG_AUTO_RESET_SYSTEM_TIMEOUT)
HI_CONST HI_U32 g_ulAutoResetSystemTimeOutCfg                   = PRODUCT_CFG_AUTO_RESET_SYSTEM_TIMEOUT;
#endif
#endif // PRODUCT_CFG_SUPPORT_CONFIG_VARIABLE

