//*****************************************************************************
//
//                  版权所有 (C), 2001-2011, 华为技术有限公司
//
//*****************************************************************************
//  文 件 名   : cts_debug.h
//  版 本 号   : V1.0 
//  作    者   : 
//  生成日期   : 2014年05月09日
//  功能描述   : 
//  函数列表   : 无
//  修改历史   : 
//*****************************************************************************

#ifndef __CTS_DEBUG_H__
#define __CTS_DEBUG_H__

//*****************************************************************************
#include "app_common.h"

typedef enum
{
    CTS_FILE_LOG_FLAG_001 = 1,
    CTS_FILE_LOG_FLAG_002,
    CTS_FILE_LOG_FLAG_003,
    CTS_FILE_LOG_FLAG_004,
    CTS_FILE_LOG_FLAG_005,
    CTS_FILE_LOG_FLAG_006,
    CTS_FILE_LOG_FLAG_007,
    CTS_FILE_LOG_FLAG_008,
    CTS_FILE_LOG_FLAG_009,
    CTS_FILE_LOG_FLAG_010,
    CTS_FILE_LOG_FLAG_011,
    CTS_FILE_LOG_FLAG_012,
    CTS_FILE_LOG_FLAG_013,
    CTS_FILE_LOG_FLAG_014,
    CTS_FILE_LOG_FLAG_015,
    CTS_FILE_LOG_FLAG_016,
    CTS_FILE_LOG_FLAG_017,
    CTS_FILE_LOG_FLAG_018,
    CTS_FILE_LOG_FLAG_019,
    CTS_FILE_LOG_FLAG_020,
    CTS_FILE_LOG_FLAG_021,
    CTS_FILE_LOG_FLAG_022,
    CTS_FILE_LOG_FLAG_023,
    CTS_FILE_LOG_FLAG_024,
    CTS_FILE_LOG_FLAG_025,
    CTS_FILE_LOG_FLAG_026,
    CTS_FILE_LOG_FLAG_027,
    CTS_FILE_LOG_FLAG_028,
    CTS_FILE_LOG_FLAG_029,
    CTS_FILE_LOG_FLAG_030,
    CTS_FILE_LOG_FLAG_031,
    CTS_FILE_LOG_FLAG_032,
    CTS_FILE_LOG_FLAG_033,
    CTS_FILE_LOG_FLAG_034,
    CTS_FILE_LOG_FLAG_035,
    CTS_FILE_LOG_FLAG_036,
    CTS_FILE_LOG_FLAG_037,
    CTS_FILE_LOG_FLAG_038,
    CTS_FILE_LOG_FLAG_039,
    CTS_FILE_LOG_FLAG_040,
    CTS_FILE_LOG_FLAG_041,
    CTS_FILE_LOG_FLAG_042,
    CTS_FILE_LOG_FLAG_043,
    CTS_FILE_LOG_FLAG_044,
    CTS_FILE_LOG_FLAG_045,
    CTS_FILE_LOG_FLAG_046,
    CTS_FILE_LOG_FLAG_047,
    CTS_FILE_LOG_FLAG_048,
    CTS_FILE_LOG_FLAG_049,
    CTS_FILE_LOG_FLAG_050,
    CTS_FILE_LOG_FLAG_051,
    CTS_FILE_LOG_FLAG_052,
    CTS_FILE_LOG_FLAG_053,
    CTS_FILE_LOG_FLAG_054,
    CTS_FILE_LOG_FLAG_055,
    CTS_FILE_LOG_FLAG_056,
    CTS_FILE_LOG_FLAG_057,
    CTS_FILE_LOG_FLAG_058,
    CTS_FILE_LOG_FLAG_059,
    CTS_FILE_LOG_FLAG_060,
    CTS_FILE_LOG_FLAG_061,
    CTS_FILE_LOG_FLAG_062,
    CTS_FILE_LOG_FLAG_063,
    CTS_FILE_LOG_FLAG_064,
    CTS_FILE_LOG_FLAG_065,
    CTS_FILE_LOG_FLAG_066,
    CTS_FILE_LOG_FLAG_067,
    CTS_FILE_LOG_FLAG_068,
    CTS_FILE_LOG_FLAG_069,
    CTS_FILE_LOG_FLAG_070,
    CTS_FILE_LOG_FLAG_071,
    CTS_FILE_LOG_FLAG_072,
    CTS_FILE_LOG_FLAG_073,
    CTS_FILE_LOG_FLAG_074,
    CTS_FILE_LOG_FLAG_075,
    CTS_FILE_LOG_FLAG_076,
    CTS_FILE_LOG_FLAG_077,
    CTS_FILE_LOG_FLAG_078,
    CTS_FILE_LOG_FLAG_079,
    CTS_FILE_LOG_FLAG_080,
    CTS_FILE_LOG_FLAG_081,
    CTS_FILE_LOG_FLAG_082,
    CTS_FILE_LOG_FLAG_083,
    CTS_FILE_LOG_FLAG_084,
    CTS_FILE_LOG_FLAG_085,
    CTS_FILE_LOG_FLAG_086,
    CTS_FILE_LOG_FLAG_087,
    CTS_FILE_LOG_FLAG_088,
    CTS_FILE_LOG_FLAG_089,
    CTS_FILE_LOG_FLAG_090,
    CTS_FILE_LOG_FLAG_091,
    CTS_FILE_LOG_FLAG_092,
    CTS_FILE_LOG_FLAG_093,
    CTS_FILE_LOG_FLAG_094,
    CTS_FILE_LOG_FLAG_095,
    CTS_FILE_LOG_FLAG_096,
    CTS_FILE_LOG_FLAG_097,
    CTS_FILE_LOG_FLAG_098,
    CTS_FILE_LOG_FLAG_099,
    CTS_FILE_LOG_FLAG_100,
    CTS_FILE_LOG_FLAG_101,
    CTS_FILE_LOG_FLAG_102,
    CTS_FILE_LOG_FLAG_103,
    CTS_FILE_LOG_FLAG_104,
    CTS_FILE_LOG_FLAG_105,
    CTS_FILE_LOG_FLAG_106,
    CTS_FILE_LOG_FLAG_107,
    CTS_FILE_LOG_FLAG_108,
    CTS_FILE_LOG_FLAG_109,
    CTS_FILE_LOG_FLAG_110,
    CTS_FILE_LOG_FLAG_111,
    CTS_FILE_LOG_FLAG_112,
    CTS_FILE_LOG_FLAG_113,
    CTS_FILE_LOG_FLAG_114,
    CTS_FILE_LOG_FLAG_115,
    CTS_FILE_LOG_FLAG_116,
    CTS_FILE_LOG_FLAG_117,
    CTS_FILE_LOG_FLAG_118,
    CTS_FILE_LOG_FLAG_119,
    CTS_FILE_LOG_FLAG_120,
    CTS_FILE_LOG_FLAG_121,
    CTS_FILE_LOG_FLAG_122,
    CTS_FILE_LOG_FLAG_123,
    CTS_FILE_LOG_FLAG_124,
    CTS_FILE_LOG_FLAG_125,
    CTS_FILE_LOG_FLAG_126,
    CTS_FILE_LOG_FLAG_127,
    CTS_FILE_LOG_FLAG_128,
    CTS_FILE_LOG_FLAG_129,
    CTS_FILE_LOG_FLAG_130,
    CTS_FILE_LOG_FLAG_131,
    CTS_FILE_LOG_FLAG_132,
    CTS_FILE_LOG_FLAG_133,
    CTS_FILE_LOG_FLAG_134,
    CTS_FILE_LOG_FLAG_135,
    CTS_FILE_LOG_FLAG_136,
    CTS_FILE_LOG_FLAG_137,
    CTS_FILE_LOG_FLAG_138,
    CTS_FILE_LOG_FLAG_139,
    CTS_FILE_LOG_FLAG_140,
    CTS_FILE_LOG_FLAG_141,
    CTS_FILE_LOG_FLAG_142,
    CTS_FILE_LOG_FLAG_143,
    CTS_FILE_LOG_FLAG_144,    
    CTS_FILE_LOG_FLAG_145,
    CTS_FILE_LOG_FLAG_146,
    CTS_FILE_LOG_FLAG_147,
    CTS_FILE_LOG_FLAG_148,
    CTS_FILE_LOG_FLAG_149,
    CTS_FILE_LOG_FLAG_150,
}CTS_LOG_FLAG_ENUM;

void printRet(HI_U16 ret)
{
	switch(ret)
		{
		//system error
		case HI_ERR_SUCCESS:
			CTS_PRINT0("HI_ERR_SUCCESS");
			break;
		case HI_ERR_INVALID_PARAMETER:
			CTS_PRINT0("HI_ERR_INVALID_PARAMETER");
			break;
		case HI_ERR_INVALID_ID:
			CTS_PRINT0("HI_ERR_INVALID_ID");
			break;
		case HI_ERR_NO_INITILIZATION:
			CTS_PRINT0("HI_ERR_NO_INITILIZATION");
			break;
		case HI_ERR_NOT_FOUND:
			CTS_PRINT0("HI_ERR_NOT_FOUND");
			break;
		case HI_ERR_FULL:   
			CTS_PRINT0("HI_ERR_FULL");
			break;
		case HI_ERR_INSUFFICIENT_BUFFER:
			CTS_PRINT0("HI_ERR_INSUFFICIENT_BUFFER");
			break;
		case HI_ERR_CONSUMED:
			CTS_PRINT0("HI_ERR_CONSUMED");
			break;
		case HI_ERR_CONTINUE:
			CTS_PRINT0("HI_ERR_CONTINUE");
			break;
		case HI_ERR_TOO_SMALL_BUFFER:         
			CTS_PRINT0("HI_ERR_TOO_SMALL_BUFFER");
			break;
		case HI_ERR_NOT_FREEE_SPACE:          
			CTS_PRINT0("HI_ERR_NOT_FREEE_SPACE");
			break;
		case HI_ERR_NO_MORE_DATA:
			CTS_PRINT0("HI_ERR_NO_MORE_DATA");
			break;
		case HI_ERR_MALLOC_FAILUE:
			CTS_PRINT0("HI_ERR_MALLOC_FAILUE");
			break;
		case HI_ERR_NOT_ENOUGH_MEMORY:
			CTS_PRINT0("HI_ERR_NOT_ENOUGH_MEMORY");
			break;
		case HI_ERR_INVALID_HEAP_ADDR:
			CTS_PRINT0("HI_ERR_INVALID_HEAP_ADDR");
			break;
		case HI_ERR_SHUTDOWN:
			CTS_PRINT0("HI_ERR_SHUTDOWN");
			break;
		case HI_ERR_NOT_CONNECT:
			CTS_PRINT0("HI_ERR_NOT_CONNECT");
			break;
		case HI_ERR_BUSY:
			CTS_PRINT0("HI_ERR_BUSY");
			break;
		case HI_ERR_INITILIZATION:
			CTS_PRINT0("HI_ERR_INITILIZATION");
			break;
		case HI_ERR_POWER_ON_PROCESS:
			CTS_PRINT0("HI_ERR_POWER_ON_PROCESS");
			break;
		case HI_ERR_SKIP:
			CTS_PRINT0("HI_ERR_SKIP");
			break;
		case HI_ERR_NOT_REGISTER:
			CTS_PRINT0("HI_ERR_NOT_REGISTER");
			break;
		case HI_ERR_TOO_LARGE_FRAME:
			CTS_PRINT0("HI_ERR_TOO_LARGE_FRAME");
			break;
		case HI_ERR_NO_OS_RES_INIT:
			CTS_PRINT0("HI_ERR_NO_OS_RES_INIT");
			break;
		case HI_ERR_NO_INIT_APP_OS_RES:
			CTS_PRINT0("HI_ERR_NO_INIT_APP_OS_RES");
			break;
		case HI_ERR_INITILIZATION_ALREADY:
			CTS_PRINT0("HI_ERR_INITILIZATION_ALREADY");
			break;
		case HI_ERR_RAM_ALIGN:
			CTS_PRINT0("HI_ERR_RAM_ALIGN");
			break;
		case HI_ERR_NOT_SUPPORT:
			CTS_PRINT0("HI_ERR_NOT_SUPPORT");
			break;
		case HI_ERR_NOT_EXIST:
			CTS_PRINT0("HI_ERR_NOT_EXIST");
			break;
		case HI_ERR_FEATURE_NOT_SUPPORT:
			CTS_PRINT0("HI_ERR_FEATURE_NOT_SUPPORT");
			break;
		case HI_ERR_INVALID_CHIP_TYPE:
			CTS_PRINT0("HI_ERR_INVALID_CHIP_TYPE");
			break;
		case HI_ERR_INVALID_PRODUCT_TYPE:
			CTS_PRINT0("HI_ERR_INVALID_PRODUCT_TYPE");
			break;
		case HI_ERR_INVALID_PRODUCT_CONFIG:
			CTS_PRINT0("HI_ERR_INVALID_PRODUCT_CONFIG");
			break;
		case HI_ERR_WRITE_FLASH_FAILURE:
			CTS_PRINT0("HI_ERR_WRITE_FLASH_FAILURE");
			break;
		case HI_ERR_ACCESS_DENIED:
			CTS_PRINT0("HI_ERR_ACCESS_DENIED");
			break;
		case HI_ERR_MEM_POOL_REQUEST_FAIL:
			CTS_PRINT0("HI_ERR_MEM_POOL_REQUEST_FAIL");
			break;
		case HI_ERR_NOT_SUPPORT_ID:
			CTS_PRINT0("HI_ERR_NOT_SUPPORT_ID");
			break;
		case HI_ERR_UNAVAILABLE:
			CTS_PRINT0("HI_ERR_UNAVAILABLE");
			break;
		case HI_ERR_TIMEOUT:
			CTS_PRINT0("HI_ERR_TIMEOUT");
			break;
		case HI_ERR_CFG_NOT_ALLOW:
			CTS_PRINT0("HI_ERR_CFG_NOT_ALLOW");
			break;
		case HI_ERR_BAD_DATA:
			CTS_PRINT0("HI_ERR_CFG_NOT_ALLOW");
			break;
		case HI_ERR_HEAP_INIT_FAIL:
			CTS_PRINT0("HI_ERR_HEAP_INIT_FAIL");
			break;
		case HI_ERR_OSRES_INIT_FAIL:
			CTS_PRINT0("HI_ERR_OSRES_INIT_FAIL");
			break;
		case HI_ERR_TASK_INIT_FAIL:
			CTS_PRINT0("HI_ERR_TASK_INIT_FAIL");
			break;
		case HI_ERR_ADDR_ACCESS_FAILURE:
			CTS_PRINT0("HI_ERR_ADDR_ACCESS_FAILURE");
			break;
		case HI_ERR_INVALID_TYPE:
			CTS_PRINT0("HI_ERR_INVALID_TYPE");
			break;
		case HI_ERR_TOO_LARGE_DATA:
			CTS_PRINT0("HI_ERR_TOO_LARGE_DATA");
			break;
		case HI_ERR_INVALID_CODE_ADDR:
			CTS_PRINT0("HI_ERR_INVALID_CODE_ADDR");
			break;
		case HI_ERR_INVALID_RAM_ADDR:
			CTS_PRINT0("HI_ERR_INVALID_RAM_ADDR");
			break;
		case HI_ERR_INVALID_PERIOD:
			CTS_PRINT0("HI_ERR_INVALID_PERIOD");
			break;
		case HI_ERR_BAD_FRAME:
			CTS_PRINT0("HI_ERR_BAD_FRAME");
			break;
		case HI_ERR_BAD_FRAME_SIZE:
			CTS_PRINT0("HI_ERR_BAD_FRAME_SIZE");
			break;
		case HI_ERR_BAD_FRAME_PORT:
			CTS_PRINT0("HI_ERR_BAD_FRAME_PORT");
			break;
		case HI_ERR_OBJ_NOT_FOUND:
			CTS_PRINT0("HI_ERR_OBJ_NOT_FOUND");
			break;
		case HI_ERR_NV_CFG_DISABLE:
			CTS_PRINT0("HI_ERR_NV_CFG_DISABLE");
			break;
		case HI_ERR_EXIST:
			CTS_PRINT0("HI_ERR_EXIST");
			break;
		case HI_ERR_REGISTER_PARAM:
			CTS_PRINT0("HI_ERR_REGISTER_PARAM");
			break;
		case HI_ERR_AUTH_INVALID:
			CTS_PRINT0("HI_ERR_AUTH_INVALID");
			break;
		case HI_ERR_CHECKSUM_INVALID:
			CTS_PRINT0("HI_ERR_CHECKSUM_INVALID");
			break;
		case HI_ERR_PROTO_INVALID:
			CTS_PRINT0("HI_ERR_PROTO_INVALID");
			break;

		//
		case HI_ERR_LOADFILE_NEED_FIRST_BLOCK:
			CTS_PRINT0("HI_ERR_LOADFILE_NEED_FIRST_BLOCK");
			break;
		case HI_ERR_DIAG_CMD_SIZE_INVALID:
			CTS_PRINT0("HI_ERR_DIAG_CMD_SIZE_INVALID");
			break;

		//
		case HI_ERR_QUEUE_FULL:
			CTS_PRINT0("HI_ERR_QUEUE_FULL");
			break;
		case HI_ERR_QUEUE_NOT_EXIST:    
			CTS_PRINT0("HI_ERR_QUEUE_NOT_EXIST");
			break;
		case HI_ERR_INVALID_TASK_ID:
			CTS_PRINT0("HI_ERR_INVALID_TASK_ID");
			break;
		case HI_ERR_INVALID_TASK_QUEUE:
			CTS_PRINT0("HI_ERR_INVALID_TASK_QUEUE");
			break;
		case HI_ERR_QUEUE_EMPTY:
			CTS_PRINT0("HI_ERR_QUEUE_EMPTY");
			break;
		case HI_ERR_CREATE_SEM_FAIL:
			CTS_PRINT0("HI_ERR_CREATE_SEM_FAIL");
			break;
		case HI_ERR_EVT_EMPTY:
			CTS_PRINT0("HI_ERR_EVT_EMPTY");
			break;
		case HI_ERR_APP_CHL_UNKNOWN:
			CTS_PRINT0("HI_ERR_APP_CHL_UNKNOWN");
			break;
		case HI_ERR_INVALID_TASK_PRIO:
			CTS_PRINT0("HI_ERR_INVALID_TASK_PRIO");
			break;
		//
		case HI_ERR_NV_NOT_SUPPORT_ID:
			CTS_PRINT0("HI_ERR_NV_NOT_SUPPORT_ID");
			break;
		case HI_ERR_NV_ERROR_READ:
			CTS_PRINT0("HI_ERR_NV_ERROR_READ");
			break;
		case HI_ERR_NV_NOT_SUPPORT_LENTH:
			CTS_PRINT0("HI_ERR_NV_NOT_SUPPORT_LENTH");
			break;
		case HI_ERR_NV_BAD_BLOCK:
			CTS_PRINT0("HI_ERR_NV_BAD_BLOCK");
			break;
		case HI_ERR_NV_ERROR_WRITE:
			CTS_PRINT0("HI_ERR_NV_ERROR_WRITE");
			break;
		case HI_ERR_NO_MORE_MEMORY:
			CTS_PRINT0("HI_ERR_NO_MORE_MEMORY");
			break;
		case HI_ERR_OS_MSG_BODY_NULL:
			CTS_PRINT0("HI_ERR_OS_MSG_BODY_NULL");
			break;
		case HI_ERR_NV_INVALID_INDEX:
			CTS_PRINT0("HI_ERR_NV_INVALID_INDEX");
			break;
		//
		case HI_ERR_FLASH_SYS_CALL:
			CTS_PRINT0("HI_ERR_FLASH_SYS_CALL");
			break;
		case HI_ERR_UART_SYS_CALL:
			CTS_PRINT0("HI_ERR_UART_SYS_CALL");
			break;
		case HI_ERR_FLASH_OPEN_FAIL:
			CTS_PRINT0("HI_ERR_FLASH_OPEN_FAIL");
			break;

		case HI_ERR_QUEUE_NOT_OPEN:
			CTS_PRINT0("HI_ERR_QUEUE_NOT_OPEN");
			break;
		case HI_ERR_QUEUE_UNAVAILABLE:
			CTS_PRINT0("HI_ERR_QUEUE_UNAVAILABLE");
			break;
		case HI_ERR_QUEUE_SHUTDOWN:
			CTS_PRINT0("HI_ERR_QUEUE_SHUTDOWN");
			break;
		//
		case HI_ERR_NV_ITEM_IS_EMPTY:
			CTS_PRINT0("HI_ERR_NV_ITEM_IS_EMPTY");
			break;
		case HI_ERR_NV_FLASH_FULL:
			CTS_PRINT0("HI_ERR_NV_FLASH_FULL");
			break;
		case HI_ERR_NV_NOT_SUPPORT_UPDATA:
			CTS_PRINT0("HI_ERR_NV_NOT_SUPPORT_UPDATA");
			break;
		case HI_ERR_NV_NEED_BACK_FAIL:
			CTS_PRINT0("HI_ERR_NV_NEED_BACK_FAIL");
			break;
		case HI_ERR_NV_INVALID_NVFILE:
			CTS_PRINT0("HI_ERR_NV_INVALID_NVFILE");
			break;
		case HI_ERR_NV_INVALID_NVFILE_SECTOR_BAD:
			CTS_PRINT0("HI_ERR_NV_INVALID_NVFILE_SECTOR_BAD");
			break;
		case HI_ERR_NV_ITEM_TOO_LARGE:
			CTS_PRINT0("HI_ERR_NV_ITEM_TOO_LARGE");
			break;

		//升级错误
		case HI_ERR_SUM_ONLY_NVCOPY_OK:
			CTS_PRINT0("HI_ERR_SUM_ONLY_NVCOPY_OK");
			break;
		case HI_ERR_SUM_BACK_OK:
			CTS_PRINT0("HI_ERR_SUM_BACK_OK");
			break;
		case HI_ERR_SUM_BACK_FAIL:
			CTS_PRINT0("HI_ERR_SUM_BACK_FAIL");
			break;
		case HI_ERR_SUM_BACK_NO_VERSION:
			CTS_PRINT0("HI_ERR_SUM_BACK_NO_VERSION");
			break;
		case HI_ERR_SUM_UPDATE_RESET_FAILUE:
			CTS_PRINT0("HI_ERR_SUM_UPDATE_RESET_FAILUE");
			break;
		case HI_ERR_SUM_NOT_NETWORKED:
			CTS_PRINT0("HI_ERR_SUM_NOT_NETWORKED");
			break;
		case HI_ERR_SUM_UPG_FILE_CRC_INCORRECT:
			CTS_PRINT0("HI_ERR_SUM_UPG_FILE_CRC_INCORRECT");
			break;
		case HI_ERR_SUM_UPG_FILE_VRC_INCORRECT:
			CTS_PRINT0("HI_ERR_SUM_UPG_FILE_VRC_INCORRECT");
			break;
		case HI_ERR_SUM_READ_BSN_NV_ERROR:
			CTS_PRINT0("HI_ERR_SUM_READ_BSN_NV_ERROR");
			break;
		case HI_ERR_SUM_VER_CP_NEG_NOT_FORCE_UPG:
			CTS_PRINT0("HI_ERR_SUM_VER_CP_NEG_NOT_FORCE_UPG");
			break;
		case HI_ERR_SUM_UPG_TIMEOUT:
			CTS_PRINT0("HI_ERR_SUM_UPG_TIMEOUT");
			break;
		case HI_ERR_SUM_SOFT_RST_CAUSE_UPG_STOP:
			CTS_PRINT0("HI_ERR_SUM_SOFT_RST_CAUSE_UPG_STOP");
			break;
//		case HI_ERR_SUM_INVALID_UPG_ID:
//			CTS_PRINT0("HI_ERR_SUM_INVALID_UPG_ID");
//			break;

		//
		case HI_ERR_CIPHER_INVAL:
                CTS_PRINT0("HI_ERR_CIPHER_INVAL");
                break;
		case HI_ERR_CIPHER_ADDRESS_INFORMAL:
                CTS_PRINT0("HI_ERR_CIPHER_ADDRESS_INFORMAL");
                break;
		case HI_ERR_CIPHER_CACHE_ALIGN:
                CTS_PRINT0("HI_ERR_CIPHER_CACHE_ALIGN");
                break;
		default:
			CTS_PRINT1("default ret=%d",ret);                  
		}
}

#endif // __CTS_DEBUG_H__

