
#ifndef __DRV_DFX_STR_H__
#define __DRV_DFX_STR_H__
#include <hi_types.h>
#include <hi_mdm_types.h>
HI_EXTERN HI_CONST HI_CHAR STR_IND_NOT_ENOUGH_MEMORY[];
HI_EXTERN HI_CONST HI_CHAR STR_IND_PARAM_WRONG[];
HI_EXTERN HI_CONST HI_CHAR STR_IND_SUCCESS[];
HI_EXTERN HI_CONST HI_CHAR STR_IND_FAIL[];
HI_EXTERN HI_CONST HI_CHAR STR_IND_NOT_SUPPORT[];
HI_EXTERN HI_CONST HI_CHAR STR_IND_HELP[];
HI_EXTERN HI_CONST HI_CHAR STR_IND_INVALID_ADDR[];
#endif

